name: TinyHtmlBuilder
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  yaml: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
executables:
  aqueduct4s:
